apiVersion: v1
kind: Service
metadata:
  name: rails-service
  namespace: devops-ror-app
  labels:
    app: rails-app
spec:
  selector:
    app: rails-app
  ports:
    - port: 3000       # Port exposed inside the cluster
      targetPort: 3000 # Port your Rails container listens on
  type: ClusterIP       # Internal service (default type)
