apiVersion: v1
kind: Secret
metadata:
  name: rails-secret
  namespace: devops-ror-app
type: Opaque
stringData:
  RDS_DB_NAME: "devopsappdb"
  RDS_USERNAME: "postgres"
  RDS_PASSWORD: "Admin123"       
  RDS_HOSTNAME: "devops-db.cdq22sqq85xa.ap-south-1.rds.amazonaws.com"
  RDS_PORT: "5432"
  S3_BUCKET_NAME: "mallowtech-devops-rorapp-testbucket"
  S3_REGION_NAME: "ap-south-1"
  LB_ENDPOINT: "a844a55c0fe9641b9996761d987cec80-1136077880.ap-south-1.elb.amazonaws.com"
